### ISSUE TITLE
Сreate a project documentation.

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#14] opened 2023-04-28 07:11 UTC
### DoD:

The draft of the rules and workflow for the board.

The board consists of **5 columns:**

1. **Common backlog** - includes all tasks that should be done.
2. **Sprint backlog** - includes the list of tasks for the current sprint.
3. **In Progress** - the list of tasks that the team works on.
4. **In Review** - the list of tasks that are under review process.
5. **Done** - the list of tasks that successfully merged to `Main` branch.

The issue moves from left to right and can't skip any step (board section). 
The main flow is `Common backlog` -> `Sprint backlog` -> `In progress` -> `In review` -> `Done`.

### The process of the issue creating and adding to Common backlog

Every issue is placed in a common backlog when it is created. 
The issue should contain a clear title and description with definitions of done (_DoD_). 
Select necessary labels, if applicable.
Don't forget to link the project `Repository`.

### Sprint backlog

Before sprint planning the issues place into Sprint backlog by PM. 
During the sprint planning process, the issues from the sprint backlog are estimated (labels with estimation are assigned), and the assignee is defined.
The field `milestone`, and labels with estimation points should be filled for the issues after sprint planning.

###  in Progress
When the work on the task starts it moves to `in Progress` section and stays there until PR will be opened. 

###  in Review
When the work on the task is done, the PR is opened and waited for the review process, the issue is placed in the `in Review` section.
Don't forget to link the opened PR with the issue.

###  Done.
The issues have successfully gone through the review process and merged into Main branch can be moved to the `Done` section.

**Comment by NadzeyaShpakouskaya** [comment] 2023-04-30 10:12
The draft of the rules and workflow for the board.

The board consists of **5 columns:**

1. **Common backlog** - includes all tasks that should be done.
2. **Sprint backlog** - includes the list of tasks for the current sprint.
3. **In Progress** - the list of tasks that the team works on.
4. **In Review** - the list of tasks that are under review process.
5. **Done** - the list of tasks that successfully merged to `Main` branch.

The issue moves from left to right and can't skip any step (board section). 
The main flow is `Common backlog` -> `Sprint backlog` -> `In progress` -> `In review` -> `Done`.

### The process of the issue creating and adding to Common backlog

Every issue is placed in a common backlog when it is created. 
The issue should contain a clear title and description with definitions of done (_DoD_). 
Select necessary labels, if applicable.
Don't forget to link the project `Repository`.


### Sprint backlog

Before sprint planning the issues place into Sprint backlog by PM. 
During the sprint planning process, the issues from the sprint backlog are estimated (labels with estimation are assigned), and the assignee is defined.
The fields `assignees`, `milestone`, and labels with estimation points should be filled for the issues after sprint planning.

###  in Progress
When the work on the task starts it moves to `in Progress` section and stays there until PR will be opened. 

###  in Review
When the work on the task is done, the PR is opened and waited for the review process, the issue is placed in the `in Review` section.
Don't forget to link the opened PR with the issue.


###  Done.
The issues have successfully gone through the review process and merged into Main branch can be moved to the `Done` section.

**Comment by iBYarchitect** [comment] 2023-05-01 08:03
Update to DoD:
- create Changelog
- create release notes

**Closed** 2023-05-11 16:49 UTC
Labels: documentation, EST: 2
